### ISSUE TITLE
How do i win this match??

### ISSUE THREAD

**Issue by jakobdo** [thedemonhunter/Northmyth#9]
![image](https://user-images.githubusercontent.com/278270/39263989-f7d58e8a-48c3-11e8-8547-b6cb50983448.png)

Chrome - OSX

**Comment by jakobdo** [comment]
And this: 
![image](https://user-images.githubusercontent.com/278270/39264091-47c3f7c4-48c4-11e8-85ac-50de3586da91.png)

**Comment by thedemonhunter** [comment]
just fixed it :)
